# Generated by Django 4.2.5 on 2023-09-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maintopic_section_forumpost_image_subtopic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
