# Generated by Django 4.2.5 on 2023-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
