# Generated by Django 4.2.5 on 2023-10-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_contactus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.forumpost')),
                ('users', models.ManyToManyField(related_name='flaggedPosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
