# Generated by Django 4.2.5 on 2023-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_flaggedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
