# Generated by Django 4.2.5 on 2023-10-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_achievement_users_account_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
