# Generated by Django 4.2.5 on 2023-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_account_followers_account_followerscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facebookLink',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='youtubeLink',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
