# Generated by Django 4.2.5 on 2023-10-11 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_account_facebooklink_account_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='main.achievement'),
        ),
        migrations.AlterField(
            model_name='account',
            name='facebookLink',
            field=models.CharField(default='Empty', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='youtubeLink',
            field=models.CharField(default='Empty', max_length=150),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searchHistories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
