# Generated by Django 4.2.5 on 2023-10-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_crag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crags',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Crags',
        ),
    ]
