# Generated by Django 4.2.5 on 2023-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_crags_country_delete_country_delete_crags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='desc',
            field=models.TextField(),
        ),
    ]
