# Generated by Django 4.2.5 on 2023-10-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_crag_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
