# Generated by Django 4.2.5 on 2023-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
