# Generated by Django 4.2.5 on 2023-10-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='savedMainTopics',
            field=models.ManyToManyField(blank=True, related_name='accountMT', to='main.maintopic'),
        ),
        migrations.AddField(
            model_name='account',
            name='savedSubTopic',
            field=models.ManyToManyField(blank=True, related_name='accountST', to='main.maintopic'),
        ),
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(default='', null=True),
        ),
    ]
