# Generated by Django 4.2.5 on 2023-10-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_account_savedmaintopics_account_savedsubtopic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='savedSubTopic',
            new_name='savedSubTopics',
        ),
    ]
