# Generated by Django 4.2.5 on 2023-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_savedsubtopic_account_savedsubtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='savedSubTopics',
            field=models.ManyToManyField(blank=True, related_name='accountST', to='main.subtopic'),
        ),
    ]
