# Generated by Django 4.2.5 on 2023-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_comment_quotings'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='totalView',
            field=models.BigIntegerField(default=0),
        ),
    ]
