# Generated by Django 4.2.5 on 2023-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_forumpost_totalview'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintopic',
            name='totalView',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='totalView',
            field=models.BigIntegerField(default=0),
        ),
    ]
