# Generated by Django 4.2.5 on 2023-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_tag_notification_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='showing',
            field=models.BooleanField(default=False),
        ),
    ]
