# Generated by Django 4.2.5 on 2023-10-17 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0035_badge_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
    ]
