# Generated by Django 4.2.5 on 2023-10-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_badge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='maintopics',
            field=models.ManyToManyField(related_name='tags', to='main.maintopic'),
        ),
        migrations.AddField(
            model_name='tag',
            name='subtopics',
            field=models.ManyToManyField(related_name='tags', to='main.subtopic'),
        ),
    ]
