# Generated by Django 4.2.5 on 2023-10-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_tag_maintopics_tag_subtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='maintopics',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.maintopic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.forumpost'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.subtopic'),
        ),
    ]
