# Generated by Django 4.2.5 on 2023-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_tag_maintopics_alter_tag_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='showing',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
        migrations.AddField(
            model_name='account',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='main.badge'),
        ),
        migrations.AddField(
            model_name='account',
            name='showingBadges',
            field=models.ManyToManyField(blank=True, related_name='accountsShowing', to='main.badge'),
        ),
    ]
