# Generated by Django 4.2.5 on 2023-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_badge_showing_remove_badge_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
