# Generated by Django 4.2.5 on 2023-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_badge_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='suspended',
            new_name='accountSuspended',
        ),
        migrations.AddField(
            model_name='account',
            name='profileSuspended',
            field=models.BooleanField(default=False),
        ),
    ]
