# Generated by Django 4.2.5 on 2023-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
