# Generated by Django 4.2.5 on 2023-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_account_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingactivity',
            name='timeCompleted',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
