# Generated by Django 4.2.5 on 2023-10-25 16:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_climbingactivity_timecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
