# Generated by Django 4.2.5 on 2023-10-25 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_forumpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdraft',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
