# Generated by Django 4.2.5 on 2023-10-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_reactionemoji_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReactionEmoji',
        ),
    ]
