# Generated by Django 4.2.5 on 2023-10-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_postdraft_angrycount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aboutPosition',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='achievementPosition',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='account',
            name='historyPosition',
            field=models.IntegerField(default=2),
        ),
    ]
