# Generated by Django 4.2.5 on 2023-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_account_aboutposition_account_achievementposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='badgePosition',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='routesPosition',
            field=models.IntegerField(default=2),
        ),
    ]
