# Generated by Django 4.2.5 on 2023-10-27 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0056_remove_chat_user1_remove_chat_user2_chat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(null=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
