# Generated by Django 4.2.5 on 2023-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_account_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lastCoor',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lastCoorDate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
