# Generated by Django 4.2.5 on 2023-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_account_emergencycontactname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='premium_end',
            field=models.TextField(default='None', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='premium_mode',
            field=models.CharField(default='None', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='premium_start',
            field=models.TextField(default='None', null=True),
        ),
    ]
