# Generated by Django 4.2.5 on 2023-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_account_premium_end_account_premium_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/crags/'),
        ),
    ]
